[package]
name = "tetris"
version = "0.2.0"
authors = ["Devin Vander Stelt <devin@vstelt.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version="0.34", features=["bundled", "ttf"] }
rand = "*"
